### ISSUE TITLE
Video upload

### ISSUE THREAD

**Issue by chrisvidal** [zaxbux/oc-dostoragedriver-plugin#2]
so grateful for this plugin!

Images are uploaded properly.
However, I am facing an issue with video file upload, receiving this popup error from October: `File missing from request`
I updated the PHP in var such as `post_max_size` and `upload_max_filesize` and set a `upload_tmp_dir` as well in my digital instances, but it does not seem to be working.

any idea please?

**Comment by zaxbux** [comment]
What is the size of the video file you are uploading?

Are you using any reverse proxies?

What HTTP server are you using (Apache, Nginx, etc)?

**Comment by chrisvidal** [comment]
video is 29Mb
no reverse proxy,
Apache 2

**Comment by zaxbux** [comment]
What's your Apache upload limit?

**Comment by chrisvidal** [comment]
`post_max_size` and `upload_max_filesize` are set to 128Mb

**Comment by zaxbux** [comment]
Does uploading that file work when the driver plugin is disabled? Try test uploading the video to the local file system.

**Comment by chrisvidal** [comment]
same error with a `local` drive

**Comment by zaxbux** [comment]
It seems like there is a configuration issue on your system. I haven't been able to replicate. This plugin essentially is the same as the S3 driver, but changes some metadata on the uploaded file.

**Comment by chrisvidal** [comment]
I am running on an Ubuntu 16.04 on Digital Ocean;
It' is probably a folder permission issue that I can't manage to solve yet.
thanks for your help @zaxbux
